#!/usr/bin/bash
# @brief Setup FTorch for a different version of ICON.
#
# @description Only needed if you want to setup FTorch with a version of ICON
# like `icon-nwp/uaicon-dev-iap`. Modifies auotools build to facilitate 
# building ICON with FTorch

# Validate you are in the ICON project directory
is_icon_src_project=$(find . -type f -name "icon.f90")
is_icon_project_root=$(ls | grep externals)
if [[ -z ${is_icon_src_project} || -z ${is_icon_project_root} ]] 
then
    echo "ERROR: Could not found 'icon.f90' and/or the 'externals' directory." 
    echo "Make sure you are in the ICON project directory. Make sure you are"
    echo "not in an ICON build directory."
    exit 1 
fi

# Validate Torch installation
if [[ -z ${Torch_DIR} ]] 
then
    echo "ERROR: 'Torch_DIR' is not defined"
    echo "Please export Torch_DIR with a path to a valid Torch installation."
    echo "Note: Make sure Torch_DIR is also defined with compiling ICON in the"
    echo "the build directory."
    echo "E.g.,"
    echo "export Torch_DIR=/path/to/.venv/lib/python3.12/site-packages/torch"
    exit 1 
else
    has_torch_config=$(find ${Torch_DIR} -type f -name "TorchConfig.cmake")
    if [[ -z ${has_torch_config} ]]
    then
        echo "ERROR: Cannot find 'TorchConfig.cmake' in Torch_DIR=${Torch_DIR}"
        echo "Please check that you have a valid Torch installation."
        exit 1 
    fi
fi

echo "BEGIN: updates to support FTorch"

# Add FTorch to the submodules 
git submodule add https://github.com/Cambridge-ICCS/FTorch.git externals/FTorch

# Get the externals 
git submodule update --init 

# Checkout a tested version of FTorch
(cd externals/FTorch && git checkout -b stable ef44cf6d70edef38003dec41ee7a1b496922a1a5)

# Make changes to configure.ac to support FTorch
note="BEGIN FTorch in one place"
ftorch_configure=$(cat << EOF
###########################
# $note 
###########################
#
# NOTE: Flag for enabling FTorch... used by preprocessor directive!
#
AC_ARG_ENABLE([ftorch],
  [AS_HELP_STRING([--enable-ftorch],
     [enable FTORCH @<:@default=no@:>@])],
  [AS_IF([test x"\$enableval" != xno], [enable_ftorch=yes])],
  [enable_ftorch=no])

#
# NOTE: Provides external ftorch flag for config 
#
AC_ARG_WITH([external-ftorch],
  [AS_HELP_STRING([--with-external-ftorch],
     [use external FTORCH library @<:@default=no@:>@])],
  [AS_IF([test x"\$withval" != xno], [with_external_ftorch=yes])],
  [with_external_ftorch=no])

#
# NOTE: Preprocessor directive for FTorch
#
AS_VAR_IF([enable_ftorch], [yes],
  [AS_VAR_APPEND([FCFLAGS], [" \${FC_PP_DEF}__FTORCH"])])

# 
# NOTE: Provides check for FTorch functionality
#
AS_IF([test "x\$enable_ftorch" = xyes && test "x\$with_external_ftorch" = xyes],
  [AS_VAR_APPEND([FCFLAGS], [" \${ftorch_FCFLAGS}"])
     AS_VAR_APPEND([LDFLAGS], [" -L\${ftorch_LIBDIR} -Wl,-rpath,\${ftorch_LIBDIR}"])
     AS_VAR_APPEND([LIBS], [" \${ftorch_LIBS}"])
     AC_CACHE_CHECK([whether the FTORCH library is available],
     [icon_cv_have_ftorch],
     [icon_cv_have_ftorch=no
      AC_LINK_IFELSE([AC_LANG_PROGRAM([], [[
      ! From https://github.com/Cambridge-ICCS/FTorch/blob/ef44cf6d70edef38003dec41ee7a1b496922a1a5/examples/1_Tensor/tensor_manipulation.f90
      use ftorch, only: torch_kCPU, torch_kFloat32, torch_tensor, &
        torch_tensor_delete, torch_tensor_ones

      use, intrinsic :: iso_c_binding, only: c_int64_t

      ! Import the real32 type for 32-bit floating point numbers
      use, intrinsic :: iso_fortran_env, only: sp => real32

      implicit none

      ! Define some tensors
      type(torch_tensor) :: a

      ! Variables for constructing tensors with torch_tensor_ones
      integer, parameter :: ndims = 2
      integer(c_int64_t), dimension(2), parameter :: tensor_shape = [2, 3]

      ! Create a tensor of ones
      ! -----------------------
      call torch_tensor_ones(a, ndims, tensor_shape, torch_kFloat32, torch_kCPU)
      call torch_tensor_delete(a)]])],
        [icon_cv_have_ftorch=yes])])
   AS_VAR_IF([icon_cv_have_ftorch], [no],
     [AC_MSG_FAILURE([unable to link a test program using FTORCH dnl
You need to provide ftorch_FCFLAGS, ftorch_LIBS, ftorch_LIBDIR during dnl
configuration OR modify the config/*/<platform>.<compiler> FCFLAGS, LDFLAGS dnl
and LIBS manually.])])])

# 
# NOTE: Provides build options for FTorch if FTorch is built by ICON 
# 
# TODO: Currently builds FTorch as shared lib (i.e., produces libftorch.so)...
# if you migrate to static lib, then you will need to change bundled libs 
# append to libftorch.a and possibly handle providing ICON flags for LibTorch
#
AS_IF([test "x\$enable_ftorch" = xyes && test "x\$with_external_ftorch" = xno],
  [icon_subdir_srcdir="\$srcdir/externals/FTorch"
   icon_subdir_unique_file="src/ftorch.F90"
   AS_IF([test ! -r "\$icon_subdir_srcdir/\$icon_subdir_unique_file"],
     [AC_MSG_ERROR([unable to find sources of the bundled version of FTORCH dnl
library (\$icon_subdir_unique_file) in '\$icon_subdir_srcdir': provide an dnl
external version of FTORCH library (--with-external-ftorch) by setting CFLAGS, dnl
FCFLAGS, LDFLAGS and LIBS accordingly])])
   AC_ARG_VAR([ICON_FTORCH_FCFLAGS],
     [Fortran compiler flags to be appended to FCFLAGS when configuring the
bundled version of FTORCH library @<:@default=\$ICON_BUNDLED_FCFLAGS@:>@])dnl
   ICON_FTORCH_FCFLAGS=\${ICON_FTORCH_FCFLAGS-\$ICON_BUNDLED_FCFLAGS}
   AC_ARG_VAR([ICON_FTORCH_CFLAGS],
     [C compiler flags to be appended to CFLAGS when configuring the bundled
version of FTORCH library @<:@default=\$ICON_BUNDLED_CFLAGS@:>@])dnl
   ICON_FTORCH_CFLAGS=\${ICON_FTORCH_CFLAGS-\$ICON_BUNDLED_CFLAGS}
   ACX_SUBDIR_INIT_CMAKE([externals/FTorch],
     [no-run no-adjust-compilers no-adjust-utilities], [externals/FTorch/build],
     ['\${CMAKE}'])
   ACX_SUBDIR_REMOVE_ARGS([externals/FTorch/build],
     [-DCMAKE_C_FLAGS=*|-DCMAKE_Fortran_FLAGS=*|-DCMAKE_CXX_*=*])
   ACX_SUBDIR_APPEND_ARGS([externals/FTorch/build],
     [-DPython3_EXECUTABLE="\$PYTHON"],
     [-DCMAKE_AR="\$AR"], [-DCMAKE_RANLIB="\$RANLIB"],
     [-DCMAKE_C_FLAGS="\$subdir_CFLAGS \$ICON_FTORCH_CFLAGS \$subdir_CPPFLAGS"],
     [-DCMAKE_CXX_FLAGS=dnl
"\$subdir_CXXFLAGS \$ICON_COMIN_CXXFLAGS \$subdir_CPPFLAGS"],
     [-DCMAKE_Fortran_FLAGS="\$subdir_FCFLAGS \$ICON_FTORCH_FCFLAGS"],
     [-DCMAKE_BUILD_TYPE=Release],
     [-DCMAKE_PREFIX_PATH="\$bundled_CMAKE_PREFIX_PATH"],
     [-DBUILD_SHARED_LIBS=ON])
   AS_VAR_APPEND([bundled_CMAKE_PREFIX_PATH],
     ["\${bundled_CMAKE_PREFIX_PATH:+";"}dnl
\${icon_abs_top_builddir}/externals/FTorch/build"])
   AS_VAR_APPEND([bundled_includes],
     ["\${FC_MOD_IN}externals/FTorch/build/modules "])
   BUNDLED_LIBFILES="externals/FTorch/build/libftorch.so \$BUNDLED_LIBFILES"
   dnl Make sure ICON executable has FTorch in RPATH
   AS_VAR_APPEND([LDFLAGS], [" -Wl,-rpath,\$ac_abs_top_builddir/externals/FTorch/build"])
   AS_VAR_APPEND([icon_pvcs_subdirs], [' externals/FTorch'])])

###########################
# END FTorch in one place 
###########################
EOF
)

line_no=$(grep -n 'FCFLAGS=\"\${bundled_includes}\${FCFLAGS}\"' configure.ac | grep -oP "^\d+(?=:)")
insert=$(( line_no - 2))
if [[ -z $(grep "${note}" configure.ac) ]]
then
    echo "Adding ftorch configuration"
    awk -v n="$insert" -v text="$ftorch_configure" '
    NR == n { print text }
    { print }
    ' configure.ac > tmp 
    mv tmp configure.ac

    echo "Reconfiguring project"
    autoreconf -fvi
fi

# Add a dummy program to the IO
mo_output_event_handler_path="src/io/shared/mo_output_event_handler.f90"
note="Use FTorch"
ftorch_use=$(cat << EOF
#ifdef __FTORCH
  ! NOTE: $note 
  USE ftorch, ONLY: assignment(=), operator(+), torch_kCPU, torch_kFloat32, &
    torch_tensor, torch_tensor_delete, torch_tensor_ones, &
    torch_tensor_from_array

  USE, INTRINSIC :: iso_c_binding, only: c_int64_t

  ! Import the real32 TYPE for 32-bit floating point numbers
  USE, INTRINSIC :: iso_fortran_env, only: sp => real32
#endif
EOF
)

line_nos=($(grep -n "MODULE mo_output_event_handler" ${mo_output_event_handler_path} | grep -oP "^\d+(?=:)"))
line_no="${line_nos[0]}"
insert=$((line_no + 2))
if [[ -z $(grep "${note}" ${mo_output_event_handler_path}) ]]
then
    echo "Adding ftorch use statements"
    awk -v n="$insert" -v text="$ftorch_use" '
    NR == n { print text }
    { print }
    ' ${mo_output_event_handler_path} > tmp
    mv tmp ${mo_output_event_handler_path}
fi

# define the subroutine
note="Dummy ftorch routine"
ftorch_subroutine=$(cat << EOF
#ifdef __FTORCH
  ! NOTE: $note 
  SUBROUTINE hello_ftorch(dst)
      INTEGER, INTENT(IN) :: dst 

      ! Set working precision for reals to be 32-bit floats
      INTEGER, PARAMETER :: wp = sp

      ! Define some tensors
      TYPE(torch_tensor) :: a, b, c

      ! Variables for constructing tensors with torch_tensor_ones
      INTEGER, PARAMETER :: ndims = 2
      INTEGER(c_int64_t), DIMENSION(2), PARAMETER :: tensor_shape = [2, 3]

      ! Variables for constructing tensors with torch_tensor_from_array
      REAL(wp), DIMENSION(2,3), TARGET :: in_data, out_data

      ! Create tensors, perform simple operations, then output result
      WRITE (dst, '(3a)') "mo_output_event_handler: hello ftorch"

      CALL torch_tensor_ones(a, ndims, tensor_shape, torch_kFloat32, torch_kCPU)
      in_data(:,:) = reshape([1.0_wp, 2.0_wp, 3.0_wp, 4.0_wp, 5.0_wp, 6.0_wp], [2,3])
      CALL torch_tensor_from_array(b, in_data, torch_kCPU)
      CALL torch_tensor_from_array(c, out_data, torch_kCPU)

      c = a + b
      WRITE(dst, '(3a)') "mo_output_event_handler: sum of tensors"
      WRITE(dst, *) out_data
      WRITE(dst, '(3a)') "mo_output_event_handler: expected output: reshape([2, 3, 4, 5, 6, 7], [2,3])"

      CALL torch_tensor_delete(a)
      CALL torch_tensor_delete(b)
      CALL torch_tensor_delete(c)
  END SUBROUTINE hello_ftorch
#endif
EOF
)

line_nos=($(grep -n "CONTAINS" ${mo_output_event_handler_path} | grep -oP "^\d+(?=:)"))
line_no="${line_nos[0]}"
insert=$((line_no + 1))
if [[ -z $(grep "${note}" ${mo_output_event_handler_path}) ]]
then
    echo "Adding ftorch dummy subroutine"
    awk -v n="$insert" -v text="$ftorch_subroutine" '
    NR == n { print text }
    { print }
    ' ${mo_output_event_handler_path} > tmp
    mv tmp ${mo_output_event_handler_path}
fi

# call ftorch dummy routine
note="Call ftorch dummy routine"
call_hello_ftorch=$(cat << EOF
#ifdef __FTORCH
      ! NOTE: $note
      CALL hello_ftorch(dst)
#endif 
EOF
)

line_no=$(grep -n ".*does not write ready files.*"  ${mo_output_event_handler_path} | grep -oP "^\d+(?=:)")
insert=$((line_no))
if [[ -z $(grep "${note}" ${mo_output_event_handler_path}) ]]
then
    echo "Adding call to ftorch dummy routine"
    awk -v n="$insert" -v text="$call_hello_ftorch" '
    NR == n { print text }
    { print }
    ' ${mo_output_event_handler_path} > tmp
    mv tmp ${mo_output_event_handler_path}
fi

echo "COMPLETE!"
